name = "gleam_playground"
version = "0.1.0"
description = "Playground for Gleam written in (mostly) Gleam"

target = "javascript"
gleam = ">= 0.32.0"

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = "~> 0.31"
lustre = "~> 3.0.7"
plinth = "~> 0.1"

